import "./globals.css";
import MainHeader from "@/app/components/main-header";

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
